[package]
name = "bow"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
polars = { version = "0.46.0", features = [
    "lazy",
    "serde",
    "strings",
    "regex",
    "dtype-date",
] }
serde = "1.0.217"
serde_yml = "0.0.12"
walkdir = "2.3.2"
flexi_logger = "0.29"
log = "0.4"
